#!/usr/bin/env ruby
#^syntax detection

site "https://supermarket.getchef.com/api/v1"

cookbook 'hostsfile', '= 2.0.0'
cookbook 'apt'
cookbook 'ntp'
cookbook 'ohai'
cookbook 'openssh'
cookbook 'ssh_known_hosts'
cookbook 'ulimit'
cookbook 'java'

cookbook 'logstash', '= 0.9.2'
cookbook 'elasticsearch', '= 0.3.10'
cookbook 'java', '~> 1.35.0'
cookbook 'htpasswd', '~> 0.2.4'
cookbook 'aws',   :git => "https://github.com/the-startup-stack/aws", :ref => "978531d511405de3872b5fe60ac52f73024b268f"
cookbook 'kibana', git: 'https://github.com/lusis/chef-kibana', ref: 'dbd7ee0'

cookbook 'git', '~> 4.2.2'
cookbook 'sensu', '~> 2.9.0'
cookbook 'uchiwa'

cookbook 'graphite', '= 0.4.8'
cookbook 'statsd', git: 'git@github.com:hectcastro/chef-statsd.git'
cookbook 'collectd', git: 'git@github.com:hectcastro/chef-collectd.git'

cookbook 'rvm', '~> 0.9.4'

cookbook 'chef-sugar'
cookbook 'docker', '~> 2.0'

cookbook 'users', '~> 1.7.0'
cookbook 'mysql'
