#!/usr/bin/env ruby
#^syntax detection

site "https://supermarket.getchef.com/api/v1"

cookbook 'hostsfile', '= 2.0.0'
cookbook 'zookeeper', git: 'https://github.com/SimpleFinance/chef-zookeeper'
cookbook 'mesos', git: 'https://github.com/everpeace/cookbook-mesos'
