name             'stack-ruby-webserver'
maintainer       'The Startup Stack'
maintainer_email 'avi@avi.io'
license          'MIT'
description      'Installs/Configures stack-ruby-webserver'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'stack-deploy-user'
depends 'stack-ruby'
depends 'stack-nginx'
depends 'stack-mysql'
depends 'stack-java'
depends 'stack-nodejs'
depends 'stack-newrelic'
depends 'stack-logstash-agent'
depends 'stack-god'
depends 'stack-logrotate'
depends 'stack-packages'
