# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/vivid64"
  config.ssh.forward_agent = true
  config.omnibus.chef_version = :latest

  config.vm.define "mesos-master" do |mesos_master|
    mesos_master.vm.network "private_network", ip: "192.168.88.10"
    mesos_master.vm.hostname = "mesos-master.#{Etc.getlogin}"
  end

  config.vm.define "mesos-slave" do |mesos_slave|
    mesos_slave.vm.network "private_network", ip: "192.168.88.20"
    mesos_slave.vm.hostname = "mesos-slave.#{Etc.getlogin}"
  end
end
